baseurl = "http://hisfantor.com/recipes/"
title = "Hisfantor's Food Blog"
author = "Hisfantor"
canonifyurls = true
paginate = 5
theme = "aether"
publishDir = "docs"
languageCode = "en"

[params]
brand = "Hisfantor"
description = "Hisfantor's Food Blog"
bgimg = ""
disqusShortname = "hisfantor"