baseurl = "https://hisfantor.com/studentcooking/"
title = "Studentcooking"
author = "Hisfantor"
canonifyurls = true
paginate = 5
theme = "ather"
publishDir = "docs"
languageCode = "en"

[params]
brand = "Hisfantor"
description = "Hisfantor's Food Blog"
bgimg = ""